version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    #ports:
    #  - "5432:5432"
    restart: always
  web:
    build: .
    #image: teller2:0.1
    #command: python3 manage.py runserver 0.0.0.0:8000
    #command: /bin/bash
    #entrypoint: /entrypoint.sh
    ports:
      - "80:8000"
    depends_on:
      - db
    #env_file:
    #  - ./web.env
    restart: always
