# Generated by Django 5.0.1 on 2024-01-08 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pmethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PmethodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('name', models.CharField(max_length=200)),
                ('expense', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('memo', models.CharField(max_length=1000)),
                ('share_type', models.IntegerField(choices=[(1, 'OWN'), (2, 'SHARE'), (3, 'PAY4OTHER')])),
                ('includebalance', models.BooleanField(default=True)),
                ('includemonthlysum', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryUi',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trans.category')),
            ],
            bases=('trans.category',),
        ),
        migrations.CreateModel(
            name='CategoryGroupUi',
            fields=[
                ('categorygroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trans.categorygroup')),
            ],
            bases=('trans.categorygroup',),
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trans.categorygroup'),
        ),
        migrations.CreateModel(
            name='PmethodUi',
            fields=[
                ('pmethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trans.pmethod')),
            ],
            bases=('trans.pmethod',),
        ),
        migrations.CreateModel(
            name='PmethodGroupUi',
            fields=[
                ('pmethodgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trans.pmethodgroup')),
            ],
            bases=('trans.pmethodgroup',),
        ),
        migrations.AddField(
            model_name='pmethod',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trans.pmethodgroup'),
        ),
        migrations.CreateModel(
            name='TransUi',
            fields=[
                ('trans_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trans.trans')),
            ],
            bases=('trans.trans',),
        ),
        migrations.AddField(
            model_name='trans',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trans.category'),
        ),
        migrations.AddField(
            model_name='trans',
            name='pmethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trans.pmethod'),
        ),
        migrations.AddField(
            model_name='trans',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trans',
            name='user_pay4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
